//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duo_Log_Analyzer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastLogFetch {
            get {
                return ((string)(this["LastLogFetch"]));
            }
            set {
                this["LastLogFetch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SNSAccessKeyID {
            get {
                return ((string)(this["SNSAccessKeyID"]));
            }
            set {
                this["SNSAccessKeyID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SNSTopicARN {
            get {
                return ((string)(this["SNSTopicARN"]));
            }
            set {
                this["SNSTopicARN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SNSSecretAccessKey {
            get {
                return ((string)(this["SNSSecretAccessKey"]));
            }
            set {
                this["SNSSecretAccessKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IgnoreIPList {
            get {
                return ((string)(this["IgnoreIPList"]));
            }
            set {
                this["IgnoreIPList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DUOIKey {
            get {
                return ((string)(this["DUOIKey"]));
            }
            set {
                this["DUOIKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DuoSKey {
            get {
                return ((string)(this["DuoSKey"]));
            }
            set {
                this["DuoSKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DuoHost {
            get {
                return ((string)(this["DuoHost"]));
            }
            set {
                this["DuoHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IgnoreUsers {
            get {
                return ((string)(this["IgnoreUsers"]));
            }
            set {
                this["IgnoreUsers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IPWhoisioAPIKey {
            get {
                return ((string)(this["IPWhoisioAPIKey"]));
            }
            set {
                this["IPWhoisioAPIKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SuspiciousLocation {
            get {
                return ((bool)(this["SuspiciousLocation"]));
            }
            set {
                this["SuspiciousLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UserInBypassMode {
            get {
                return ((bool)(this["UserInBypassMode"]));
            }
            set {
                this["UserInBypassMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OutsideCountryEnabled {
            get {
                return ((bool)(this["OutsideCountryEnabled"]));
            }
            set {
                this["OutsideCountryEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UnenrolledUser {
            get {
                return ((bool)(this["UnenrolledUser"]));
            }
            set {
                this["UnenrolledUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UnenrolledUserRegExEnabled {
            get {
                return ((bool)(this["UnenrolledUserRegExEnabled"]));
            }
            set {
                this["UnenrolledUserRegExEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UnenrolledUserRegExExpression {
            get {
                return ((string)(this["UnenrolledUserRegExExpression"]));
            }
            set {
                this["UnenrolledUserRegExExpression"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool iCloudPrivateRelayEnabled {
            get {
                return ((bool)(this["iCloudPrivateRelayEnabled"]));
            }
            set {
                this["iCloudPrivateRelayEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool iCloudPrivateRelayIgnore {
            get {
                return ((bool)(this["iCloudPrivateRelayIgnore"]));
            }
            set {
                this["iCloudPrivateRelayIgnore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime ICloudPrivateRelayLastUpdate {
            get {
                return ((global::System.DateTime)(this["ICloudPrivateRelayLastUpdate"]));
            }
            set {
                this["ICloudPrivateRelayLastUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GeoAlertsEnabled {
            get {
                return ((bool)(this["GeoAlertsEnabled"]));
            }
            set {
                this["GeoAlertsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public decimal GeoAlertsDistance {
            get {
                return ((decimal)(this["GeoAlertsDistance"]));
            }
            set {
                this["GeoAlertsDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double GeoAlertsLat {
            get {
                return ((double)(this["GeoAlertsLat"]));
            }
            set {
                this["GeoAlertsLat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double GeoAlertsLong {
            get {
                return ((double)(this["GeoAlertsLong"]));
            }
            set {
                this["GeoAlertsLong"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OutsideCountryCode {
            get {
                return ((string)(this["OutsideCountryCode"]));
            }
            set {
                this["OutsideCountryCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UnenrolledARN {
            get {
                return ((string)(this["UnenrolledARN"]));
            }
            set {
                this["UnenrolledARN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UnenrolledAlertsOnlySendToUnenrolledARN {
            get {
                return ((bool)(this["UnenrolledAlertsOnlySendToUnenrolledARN"]));
            }
            set {
                this["UnenrolledAlertsOnlySendToUnenrolledARN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppVersion {
            get {
                return ((string)(this["AppVersion"]));
            }
            set {
                this["AppVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProgramErrorSNSTopic {
            get {
                return ((string)(this["ProgramErrorSNSTopic"]));
            }
            set {
                this["ProgramErrorSNSTopic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GeolocationioAPIKey {
            get {
                return ((string)(this["GeolocationioAPIKey"]));
            }
            set {
                this["GeolocationioAPIKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GeoLocationIoCheck {
            get {
                return ((bool)(this["GeoLocationIoCheck"]));
            }
            set {
                this["GeoLocationIoCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GeoLocationIoCheckOverrideAlert {
            get {
                return ((bool)(this["GeoLocationIoCheckOverrideAlert"]));
            }
            set {
                this["GeoLocationIoCheckOverrideAlert"] = value;
            }
        }
    }
}
